version: '3'

services:

  db-postgres:
    #network_mode: host
    restart: on-failure
    build:
      context: .
      dockerfile: devops/postgres.dockerfile
    command: postgres -c 'max_connections=500'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=jaspion_db
      - TZ=GMT